name: Compile and Package app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  # This job will compile the app for Windows
  windows:
    runs-on: windows-latest
    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v3
      # Install the gcc compiler
      - name: Install gcc
        run: |
          choco install mingw
      # Compile the app using CMake
      - name: Compile App
        run: |
          cmake -S app -B build -G "MinGW Makefiles"  
          cd build
          make
      - name: Package App
        run: |
          mkdir website-package
          mv app/build/webgen* website-package/
          cp -r app/templates website-package/
          cp -r app/logs website-package/
          cp -r src website-package/
          cp package.json website-package/
          cp package-lock.json website-package/
          cp README.md website-package/
          cp LICENCE.md website-package/
      # Upload the website-package folder as an artifact
      - name: Upload website-package folder
        uses: actions/upload-artifact@v2
        with:
          name: website-package-windows
          path: website-package/

  # This job will compile the app for Linux
  linux:
      runs-on: ubuntu-latest
      steps:
        # Check out the code from the repository
        - uses: actions/checkout@v3
        # Install the gcc compiler
        - name: Install gcc
          run: sudo apt-get install gcc
        # Compile the app using CMake
        - name: Compile App
          run: |
            cmake -S app -B build
            cd build
            make
        - name: Package App
          run: |
            mkdir website-package
            mv app/build/webgen* website-package/
            cp -r app/templates website-package/
            cp -r app/logs website-package/
            cp -r src website-package/
            cp package.json website-package/
            cp package-lock.json website-package/
            cp README.md website-package/
            cp LICENCE.md website-package/
        # Upload the website-package folder as an artifact
        - name: Upload website-package folder
          uses: actions/upload-artifact@v2
          with:
            name: website-package-linux
            path: website-package/

  # This job will compile the app for macOS
  macos:
    runs-on: macOS-latest
    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v3
      # Install the gcc compiler
      - name: Install gcc
        run: |
          brew install gcc
      # Compile the app using CMake
      - name: Compile App
        run: |
          cmake -S app -B build
          cd build
          make
      - name: Package App
        run: |
          mkdir website-package
          mv app/build/webgen* website-package/
          cp -r app/templates website-package/
          cp -r app/logs website-package/
          cp -r src website-package/
          cp package.json website-package/
          cp package-lock.json website-package/
          cp README.md website-package/
          cp LICENCE.md website-package/
      # Upload the website-package folder as an artifact
      - name: Upload website-package folder
        uses: actions/upload-artifact@v2
        with:
          name: website-package-darwin
          path: website-package/
